# Generated by Django 3.0.8 on 2020-08-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contactformmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='aboutus',
            new_name='about',
        ),
        migrations.AlterField(
            model_name='contactformmessage',
            name='status',
            field=models.CharField(choices=[('New', 'new'), ('Read', 'Read'), ('Closed', 'Closed')], default='New', max_length=10),
        ),
    ]
