# Generated by Django 3.0.8 on 2020-08-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200808_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
