# Generated by Django 3.0.8 on 2020-08-19 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='adress',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
